
const texts = [
    "Lake Area Tech has 30 programs of study, 15 e-degrees and serves more than 2,600 full-time, part-time and online students enrolled in the previous school year. Some of the school's longstanding programs include Agriculture, Welding, Cosmetology, Diesel, Aviation, and Nursing. The school has a 17:1 student/faculty ratio and a 99% graduate placement rate.",
    "Although the first inter-party government was now coming to an end it had a number of achievements. It proved that the country could be led by a group other than Fianna Fail. It also provided a fresh perspective after sixteen years of unbroken rule by that party.",
    "The concerto has a duration of 12 minutes and is composed in seven short connected sections, which Carter described in the program note as \"presenting the many different facets of the horn, which are most remarkable and beautiful.\"",
    "Green Pond is a small area in Polk County, Florida, south of Clermont, Florida and north of Polk City, Florida, on the edge of the Green Swamp. It was the site of a community in the 19th century. A cemetery remains.",
    "The Lord Steward or Lord Steward of the Household, in England, is an important official of the Royal Household. He is always a peer. Until 1924, he was always a member of the Government. Until 1782, the office was one of considerable political importance and carried Cabinet rank.",
    "Glen Rock was settled around a large boulder in a small valley (glen), from which it gets its name. The boulder, a glacial erratic weighing in at 570 short tons (520 t) and located where Doremus Avenue meets Rock Road, is believed to have been carried to the site by a glacier that picked up the rock fifteen thousand years ago near Peekskill, New York and carried it for 20 miles to its present location.",
    "Though royal symbols differ among the sixteen Commonwealth realms, as they are separate monarchies, the one sovereign uses the same cypher throughout all of his or her countries.",
    "In 1787, there was a sizable block of delegates who were initially opposed to the Bill of Rights. This is what a member of the Georgia delegation had to say by way of opposition; 'If we list a set of rights, some fools in the future are going to claim that people are entitled only to those rights enumerated and no others.' So the Framers knew - Were you just calling me a fool, Mr. Seaborn? - I wasn't calling you a fool, sir. The brand new state of Georgia was.",
    "I was watching a television program before, with a kind of roving moderator who spoke to a seated panel of young women who were having some sort of problem with their boyfriends - apparently, because the boyfriends had all slept with the girlfriends' mothers. And they brought the boyfriends out, and they fought, right there on television. Toby, tell me, these people don't vote, do they?"
];

export default texts;
